# Generated by Django 3.1.1 on 2020-09-23 23:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 24, 7, 23, 47, 519042), verbose_name='date published'),
        ),
    ]
